/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: prorookie123 (https://sketchfab.com/prorookie123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-golf-flag-animated-a6ebddcfff9a4c8a912551530ebfdb45
Title: Low poly Golf Flag Animated
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/models/flag/scene.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.284}
        >
          <group name="ab6305f6efde404684e7d3380aa836ffabccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="Object_4" position={[1.132, -3.052, 0]}>
                  <group name="TimeframeMainGroup">
                    <group name="Object_6">
                      <mesh
                        name="Cylinder_001_6_0"
                        geometry={nodes.Cylinder_001_6_0.geometry}
                        material={materials.Cylinder_001}
                      />
                    </group>
                  </group>
                </group>
                <group name="Object_8" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="MorphMainGroup">
                    <mesh
                      name="Plane"
                      geometry={nodes.Plane.geometry}
                      material={materials.Plane}
                      morphTargetDictionary={nodes.Plane.morphTargetDictionary}
                      morphTargetInfluences={nodes.Plane.morphTargetInfluences}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
