/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: ruth182128 (https://sketchfab.com/ruth182128)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-gold-key-fc87b71b4385435dbb7c9056ee97e614
Title: Simple Gold Key
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function Model(props) {
  const { nodes } = useGLTF("/models/key/scene.gltf");
  const groupRef = React.useRef();

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.02;
    }
  });

  const goldMaterial = new THREE.MeshStandardMaterial({
    color: "#ffd700",
    metalness: 0.9,
    roughness: 0.2,
  });

  return (
    <group {...props} ref={groupRef} dispose={null} scale={0.0025}>
      <group rotation={[-Math.PI / 1, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={goldMaterial} />
        <mesh geometry={nodes.Object_3.geometry} material={goldMaterial} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/key/scene.gltf");
